# Generated by Django 3.2.15 on 2022-11-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tccs',
            new_name='Projetor',
        ),
    ]
