# Generated by Django 3.2.15 on 2022-11-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0002_rename_tccs_projetor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetor',
            name='done',
        ),
    ]
