# Generated by Django 3.2.15 on 2022-11-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0003_remove_projetor_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetor',
            name='funcionamento',
            field=models.CharField(choices=[('func', 'Funciona'), ('estr', 'Estragado')], default='func', max_length=4),
        ),
    ]
