# Generated by Django 3.2.15 on 2022-12-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0005_auto_20221201_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('matricula', models.IntegerField(default='123456789', unique=True, verbose_name=10)),
                ('email', models.CharField(default='', max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('matricula', models.IntegerField(default='123456789', unique=True, verbose_name=10)),
                ('email', models.CharField(default='', max_length=35, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Projetor',
            new_name='Dispositivo',
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplina',
            field=models.CharField(default='Nenhuma', max_length=45),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.CharField(default='', max_length=35, unique=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='matricula',
            field=models.IntegerField(default='123456789', unique=True, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=45),
        ),
    ]
