# Generated by Django 3.2.15 on 2022-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0006_auto_20221201_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='matricula',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
